// Code generated by MockGen. DO NOT EDIT.
// Source: store/nats/nats.go
//
// Generated by this command:
//
//	mockgen -source=store/nats/nats.go -destination=store/nats/nats_mock_test.go -package=nats
//

// Package nats is a generated GoMock package.
package nats

import (
	context "context"
	reflect "reflect"

	jetstream "github.com/nats-io/nats.go/jetstream"
	gomock "go.uber.org/mock/gomock"
)

// MockNatsClientInterface is a mock of NatsClientInterface interface.
type MockNatsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNatsClientInterfaceMockRecorder
	isgomock struct{}
}

// MockNatsClientInterfaceMockRecorder is the mock recorder for MockNatsClientInterface.
type MockNatsClientInterfaceMockRecorder struct {
	mock *MockNatsClientInterface
}

// NewMockNatsClientInterface creates a new mock instance.
func NewMockNatsClientInterface(ctrl *gomock.Controller) *MockNatsClientInterface {
	mock := &MockNatsClientInterface{ctrl: ctrl}
	mock.recorder = &MockNatsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNatsClientInterface) EXPECT() *MockNatsClientInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNatsClientInterface) Create(ctx context.Context, key string, value []byte, opts ...jetstream.KVCreateOpt) (uint64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, value}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNatsClientInterfaceMockRecorder) Create(ctx, key, value any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, value}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNatsClientInterface)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockNatsClientInterface) Delete(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNatsClientInterfaceMockRecorder) Delete(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNatsClientInterface)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockNatsClientInterface) Get(ctx context.Context, key string) (jetstream.KeyValueEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(jetstream.KeyValueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNatsClientInterfaceMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNatsClientInterface)(nil).Get), ctx, key)
}

// ListKeys mocks base method.
func (m *MockNatsClientInterface) ListKeys(ctx context.Context, opts ...jetstream.WatchOpt) (jetstream.KeyLister, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListKeys", varargs...)
	ret0, _ := ret[0].(jetstream.KeyLister)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeys indicates an expected call of ListKeys.
func (mr *MockNatsClientInterfaceMockRecorder) ListKeys(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeys", reflect.TypeOf((*MockNatsClientInterface)(nil).ListKeys), varargs...)
}

// Put mocks base method.
func (m *MockNatsClientInterface) Put(ctx context.Context, key string, value []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, key, value)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockNatsClientInterfaceMockRecorder) Put(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockNatsClientInterface)(nil).Put), ctx, key, value)
}

// Status mocks base method.
func (m *MockNatsClientInterface) Status(ctx context.Context) (jetstream.KeyValueStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx)
	ret0, _ := ret[0].(jetstream.KeyValueStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockNatsClientInterfaceMockRecorder) Status(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockNatsClientInterface)(nil).Status), ctx)
}
