// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nats-io/nats.go/jetstream (interfaces: KeyValueEntry,KeyValueStatus,KeyLister)
//
// Generated by this command:
//
//	mockgen -destination=nats_interfaces_mock_test.go -package=nats github.com/nats-io/nats.go/jetstream KeyValueEntry,KeyValueStatus,KeyLister
//

// Package nats is a generated GoMock package.
package nats

import (
	reflect "reflect"
	time "time"

	jetstream "github.com/nats-io/nats.go/jetstream"
	gomock "go.uber.org/mock/gomock"
)

// MockKeyValueEntry is a mock of KeyValueEntry interface.
type MockKeyValueEntry struct {
	ctrl     *gomock.Controller
	recorder *MockKeyValueEntryMockRecorder
	isgomock struct{}
}

// MockKeyValueEntryMockRecorder is the mock recorder for MockKeyValueEntry.
type MockKeyValueEntryMockRecorder struct {
	mock *MockKeyValueEntry
}

// NewMockKeyValueEntry creates a new mock instance.
func NewMockKeyValueEntry(ctrl *gomock.Controller) *MockKeyValueEntry {
	mock := &MockKeyValueEntry{ctrl: ctrl}
	mock.recorder = &MockKeyValueEntryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyValueEntry) EXPECT() *MockKeyValueEntryMockRecorder {
	return m.recorder
}

// Bucket mocks base method.
func (m *MockKeyValueEntry) Bucket() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bucket")
	ret0, _ := ret[0].(string)
	return ret0
}

// Bucket indicates an expected call of Bucket.
func (mr *MockKeyValueEntryMockRecorder) Bucket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bucket", reflect.TypeOf((*MockKeyValueEntry)(nil).Bucket))
}

// Created mocks base method.
func (m *MockKeyValueEntry) Created() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Created")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Created indicates an expected call of Created.
func (mr *MockKeyValueEntryMockRecorder) Created() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Created", reflect.TypeOf((*MockKeyValueEntry)(nil).Created))
}

// Delta mocks base method.
func (m *MockKeyValueEntry) Delta() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delta")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Delta indicates an expected call of Delta.
func (mr *MockKeyValueEntryMockRecorder) Delta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delta", reflect.TypeOf((*MockKeyValueEntry)(nil).Delta))
}

// Key mocks base method.
func (m *MockKeyValueEntry) Key() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key")
	ret0, _ := ret[0].(string)
	return ret0
}

// Key indicates an expected call of Key.
func (mr *MockKeyValueEntryMockRecorder) Key() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockKeyValueEntry)(nil).Key))
}

// Operation mocks base method.
func (m *MockKeyValueEntry) Operation() jetstream.KeyValueOp {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Operation")
	ret0, _ := ret[0].(jetstream.KeyValueOp)
	return ret0
}

// Operation indicates an expected call of Operation.
func (mr *MockKeyValueEntryMockRecorder) Operation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Operation", reflect.TypeOf((*MockKeyValueEntry)(nil).Operation))
}

// Revision mocks base method.
func (m *MockKeyValueEntry) Revision() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revision")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Revision indicates an expected call of Revision.
func (mr *MockKeyValueEntryMockRecorder) Revision() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revision", reflect.TypeOf((*MockKeyValueEntry)(nil).Revision))
}

// Value mocks base method.
func (m *MockKeyValueEntry) Value() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockKeyValueEntryMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockKeyValueEntry)(nil).Value))
}

// MockKeyValueStatus is a mock of KeyValueStatus interface.
type MockKeyValueStatus struct {
	ctrl     *gomock.Controller
	recorder *MockKeyValueStatusMockRecorder
	isgomock struct{}
}

// MockKeyValueStatusMockRecorder is the mock recorder for MockKeyValueStatus.
type MockKeyValueStatusMockRecorder struct {
	mock *MockKeyValueStatus
}

// NewMockKeyValueStatus creates a new mock instance.
func NewMockKeyValueStatus(ctrl *gomock.Controller) *MockKeyValueStatus {
	mock := &MockKeyValueStatus{ctrl: ctrl}
	mock.recorder = &MockKeyValueStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyValueStatus) EXPECT() *MockKeyValueStatusMockRecorder {
	return m.recorder
}

// BackingStore mocks base method.
func (m *MockKeyValueStatus) BackingStore() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackingStore")
	ret0, _ := ret[0].(string)
	return ret0
}

// BackingStore indicates an expected call of BackingStore.
func (mr *MockKeyValueStatusMockRecorder) BackingStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackingStore", reflect.TypeOf((*MockKeyValueStatus)(nil).BackingStore))
}

// Bucket mocks base method.
func (m *MockKeyValueStatus) Bucket() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bucket")
	ret0, _ := ret[0].(string)
	return ret0
}

// Bucket indicates an expected call of Bucket.
func (mr *MockKeyValueStatusMockRecorder) Bucket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bucket", reflect.TypeOf((*MockKeyValueStatus)(nil).Bucket))
}

// Bytes mocks base method.
func (m *MockKeyValueStatus) Bytes() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bytes")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Bytes indicates an expected call of Bytes.
func (mr *MockKeyValueStatusMockRecorder) Bytes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bytes", reflect.TypeOf((*MockKeyValueStatus)(nil).Bytes))
}

// Config mocks base method.
func (m *MockKeyValueStatus) Config() jetstream.KeyValueConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(jetstream.KeyValueConfig)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockKeyValueStatusMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockKeyValueStatus)(nil).Config))
}

// History mocks base method.
func (m *MockKeyValueStatus) History() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History")
	ret0, _ := ret[0].(int64)
	return ret0
}

// History indicates an expected call of History.
func (mr *MockKeyValueStatusMockRecorder) History() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockKeyValueStatus)(nil).History))
}

// IsCompressed mocks base method.
func (m *MockKeyValueStatus) IsCompressed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCompressed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCompressed indicates an expected call of IsCompressed.
func (mr *MockKeyValueStatusMockRecorder) IsCompressed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCompressed", reflect.TypeOf((*MockKeyValueStatus)(nil).IsCompressed))
}

// LimitMarkerTTL mocks base method.
func (m *MockKeyValueStatus) LimitMarkerTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LimitMarkerTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// LimitMarkerTTL indicates an expected call of LimitMarkerTTL.
func (mr *MockKeyValueStatusMockRecorder) LimitMarkerTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LimitMarkerTTL", reflect.TypeOf((*MockKeyValueStatus)(nil).LimitMarkerTTL))
}

// Metadata mocks base method.
func (m *MockKeyValueStatus) Metadata() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Metadata indicates an expected call of Metadata.
func (mr *MockKeyValueStatusMockRecorder) Metadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockKeyValueStatus)(nil).Metadata))
}

// TTL mocks base method.
func (m *MockKeyValueStatus) TTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// TTL indicates an expected call of TTL.
func (mr *MockKeyValueStatusMockRecorder) TTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TTL", reflect.TypeOf((*MockKeyValueStatus)(nil).TTL))
}

// Values mocks base method.
func (m *MockKeyValueStatus) Values() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Values")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Values indicates an expected call of Values.
func (mr *MockKeyValueStatusMockRecorder) Values() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Values", reflect.TypeOf((*MockKeyValueStatus)(nil).Values))
}

// MockKeyLister is a mock of KeyLister interface.
type MockKeyLister struct {
	ctrl     *gomock.Controller
	recorder *MockKeyListerMockRecorder
	isgomock struct{}
}

// MockKeyListerMockRecorder is the mock recorder for MockKeyLister.
type MockKeyListerMockRecorder struct {
	mock *MockKeyLister
}

// NewMockKeyLister creates a new mock instance.
func NewMockKeyLister(ctrl *gomock.Controller) *MockKeyLister {
	mock := &MockKeyLister{ctrl: ctrl}
	mock.recorder = &MockKeyListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyLister) EXPECT() *MockKeyListerMockRecorder {
	return m.recorder
}

// Keys mocks base method.
func (m *MockKeyLister) Keys() <-chan string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys")
	ret0, _ := ret[0].(<-chan string)
	return ret0
}

// Keys indicates an expected call of Keys.
func (mr *MockKeyListerMockRecorder) Keys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockKeyLister)(nil).Keys))
}

// Stop mocks base method.
func (m *MockKeyLister) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockKeyListerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockKeyLister)(nil).Stop))
}
