// Code generated by mockery v1.0.0. DO NOT EDIT.

package store

import mock "github.com/stretchr/testify/mock"

// MockRistrettoClientInterface is an autogenerated mock type for the RistrettoClientInterface type
type MockRistrettoClientInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *MockRistrettoClientInterface) Get(key interface{}) (interface{}, bool) {
	ret := _m.Called(key)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(interface{}) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, value, cost
func (_m *MockRistrettoClientInterface) Set(key interface{}, value interface{}, cost int64) bool {
	ret := _m.Called(key, value, cost)

	var r0 bool
	if rf, ok := ret.Get(0).(func(interface{}, interface{}, int64) bool); ok {
		r0 = rf(key, value, cost)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
