// Code generated by MockGen. DO NOT EDIT.
// Source: store/ristretto.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRistrettoClientInterface is a mock of RistrettoClientInterface interface
type MockRistrettoClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRistrettoClientInterfaceMockRecorder
}

// MockRistrettoClientInterfaceMockRecorder is the mock recorder for MockRistrettoClientInterface
type MockRistrettoClientInterfaceMockRecorder struct {
	mock *MockRistrettoClientInterface
}

// NewMockRistrettoClientInterface creates a new mock instance
func NewMockRistrettoClientInterface(ctrl *gomock.Controller) *MockRistrettoClientInterface {
	mock := &MockRistrettoClientInterface{ctrl: ctrl}
	mock.recorder = &MockRistrettoClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRistrettoClientInterface) EXPECT() *MockRistrettoClientInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockRistrettoClientInterface) Get(key interface{}) (interface{}, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRistrettoClientInterfaceMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRistrettoClientInterface)(nil).Get), key)
}

// Set mocks base method
func (m *MockRistrettoClientInterface) Set(key, value interface{}, cost int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value, cost)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Set indicates an expected call of Set
func (mr *MockRistrettoClientInterfaceMockRecorder) Set(key, value, cost interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRistrettoClientInterface)(nil).Set), key, value, cost)
}

// Del mocks base method
func (m *MockRistrettoClientInterface) Del(key interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Del", key)
}

// Del indicates an expected call of Del
func (mr *MockRistrettoClientInterfaceMockRecorder) Del(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockRistrettoClientInterface)(nil).Del), key)
}

// Clear mocks base method
func (m *MockRistrettoClientInterface) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear
func (mr *MockRistrettoClientInterfaceMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockRistrettoClientInterface)(nil).Clear))
}
